### ISSUE TITLE
Initial sync: Error creating Monica contact: ['The selected gender id is invalid.']

### ISSUE THREAD

**Issue by Turochamp** [antonplagemann/GoogleMonicaSync#22]
Got this error when doing initial sync. In Google Contacts this entry does not have a gender entered. So don't understand why it's not valid. Is it general or specific to my Monica instance?

```
2021-07-27 11:13:08,642 INFO 'Petur V-son': Error creating Monica contact: ['The selected gender id is invalid.']
2021-07-27 11:13:08,643 ERROR Error creating Monica contact!
Traceback (most recent call last):
  File "GMSync.py", line 77, in main
    sync.startSync('initial')
  File "/home/mahs/git/GoogleMonicaSync/SyncHelper.py", line 44, in startSync
    self.__initialSync()
  File "/home/mahs/git/GoogleMonicaSync/SyncHelper.py", line 81, in __initialSync
    self.__buildSyncDatabase()
  File "/home/mahs/git/GoogleMonicaSync/SyncHelper.py", line 564, in __buildSyncDatabase
    monicaId = self.__interactiveMonicaIdSearch(googleContact)
  File "/home/mahs/git/GoogleMonicaSync/SyncHelper.py", line 1045, in __interactiveMonicaIdSearch
    monicaContact = self.__createMonicaContact(googleContact)
  File "/home/mahs/git/GoogleMonicaSync/SyncHelper.py", line 985, in __createMonicaContact
    monicaContact = self.monica.createContact(data=form.data)
  File "/home/mahs/git/GoogleMonicaSync/MonicaHelper.py", line 126, in createContact
    raise Exception("Error creating Monica contact!")
Exception: Error creating Monica contact!
```

**Comment by antonplagemann** [comment]
Hi @Turochamp,
I'm not sure on this...
The script uses the default gender types, which could have changed at your instance.
Can you send the gender types you have?
Simply log into your instance and head to https://your-monica-instance.com/api/genders
That might help diagnosing this 😊

**Comment by Turochamp** [comment]
Below is the response output. Further testing shows that every time the sync tries to create a Monica contact result is this error.

```
{
    "data": [
        {
            "id": 71764,
            "object": "gender",
            "name": "Man",
            "type": "M",
            "account": {
                "id": 24528
            },
            "created_at": "2020-10-12T20:03:02Z",
            "updated_at": "2020-10-12T20:03:02Z"
        },
        {
            "id": 71765,
            "object": "gender",
            "name": "Woman",
            "type": "F",
            "account": {
                "id": 24528
            },
            "created_at": "2020-10-12T20:03:02Z",
            "updated_at": "2020-10-12T20:03:02Z"
        },
        {
            "id": 71766,
            "object": "gender",
            "name": "Rather not say",
            "type": "O",
            "account": {
                "id": 24528
            },
            "created_at": "2020-10-12T20:03:02Z",
            "updated_at": "2020-10-12T20:03:02Z"
        }
    ],
    "links": {
        "first": "http://my-monica-instance/api/genders?page=1",
        "last": "http://my-monica-instance/api/genders?page=1",
        "prev": null,
        "next": null
    },
    "meta": {
        "current_page": 1,
        "from": 1,
        "last_page": 1,
        "links": [
            {
                "url": null,
                "label": "❮ Previous",
                "active": false
            },
            {
                "url": "http://my-monica-instance/api/genders?page=1",
                "label": "1",
                "active": true
            },
            {
                "url": null,
                "label": "Next ❯",
                "active": false
            }
        ],
        "path": "http://my-monica-instance/api/genders",
        "per_page": 15,
        "to": 3,
        "total": 3
    }
}
```

**Comment by antonplagemann** [comment]
Ok thanks, got it 👍 
I was using static values for the id as in my instance they are just `1, 2` and `3`.
Another case of assuming wrong things 😊
With 695c03e147562c27e150f719bf85638f358e8086 the ids are now dynamically fetched from the instance, that should fix it.
Would be great if you can confirm this 🙂

**Comment by Turochamp** [comment]
Tested and confirmed. :satisfied:
